import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout(props: {
  params: { locale: string };
  children: React.ReactNode;
  modal: React.ReactNode;
}) {
  console.log({
    /* This will throw an error that it's not a valid element... */
    locale: props.params.locale,
  });

  return (
    <html lang="en">
      <body className={inter.className}>
        {props.children}

        {/* This will throw an error that it's not a valid element... */}
        {props.params.locale}

        {props.modal}
      </body>
    </html>
  );
}
